version: '3.1'

services:
  exfi-db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'dev_exfi_db'
      MYSQL_USER: 'dev_exfi_db_user'
      MYSQL_PASSWORD: 'dev_exfi_db_password'
      MYSQL_ROOT_PASSWORD: 'holapa'
    ports:
      - '3308:3306'
