version: '3.1'

services:
  exfi-bot:
    depends_on:
      - exfi-db
    build:
      context: .
    environment:
      BOT_NAME: ${BOT_NAME}
      BOT_TOKEN: ${BOT_TOKEN}
      BOT_DB_USERNAME: ${BOT_DB_USERNAME}
      BOT_DB_PASSWORD: ${BOT_DB_PASSWORD}
    restart: always
  exfi-db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_USER: ${BOT_DB_USERNAME}
      MYSQL_PASSWORD: ${BOT_DB_PASSWORD}
      MYSQL_DATABASE: 'exfi_db'
      MYSQL_ROOT_PASSWORD: 'holapa'
    ports:
      - '3308:3306'
    expose:
      - '3306'